"""Bidirectional lookup between OOXML ``w:styleId`` and ``StyleIdentifier``.

Word's built-in styles have locale-independent ``styleId`` values
(e.g. ``"Heading1"``, ``"Normal"``, ``"BodyText"``) that map to
numeric ``StyleIdentifier`` constants.  This module provides the
forward (styleId -> int) and reverse (int -> styleId) tables used by
the DOCX reader and writer.
"""

from aspose.words_foss.model.enums.style import StyleIdentifier as _SI

STYLE_ID_TO_IDENTIFIER: dict[str, int] = {
    # Paragraph / character styles.
    "Normal": _SI.NORMAL,
    "Heading1": _SI.HEADING_1,
    "Heading2": _SI.HEADING_2,
    "Heading3": _SI.HEADING_3,
    "Heading4": _SI.HEADING_4,
    "Heading5": _SI.HEADING_5,
    "Heading6": _SI.HEADING_6,
    "Heading7": _SI.HEADING_7,
    "Heading8": _SI.HEADING_8,
    "Heading9": _SI.HEADING_9,
    "Index1": _SI.INDEX_1,
    "Index2": _SI.INDEX_2,
    "Index3": _SI.INDEX_3,
    "Index4": _SI.INDEX_4,
    "Index5": _SI.INDEX_5,
    "Index6": _SI.INDEX_6,
    "Index7": _SI.INDEX_7,
    "Index8": _SI.INDEX_8,
    "Index9": _SI.INDEX_9,
    "TOC1": _SI.TOC_1,
    "TOC2": _SI.TOC_2,
    "TOC3": _SI.TOC_3,
    "TOC4": _SI.TOC_4,
    "TOC5": _SI.TOC_5,
    "TOC6": _SI.TOC_6,
    "TOC7": _SI.TOC_7,
    "TOC8": _SI.TOC_8,
    "TOC9": _SI.TOC_9,
    "NormalIndent": _SI.NORMAL_INDENT,
    "FootnoteText": _SI.FOOTNOTE_TEXT,
    "CommentText": _SI.COMMENT_TEXT,
    "Header": _SI.HEADER,
    "Footer": _SI.FOOTER,
    "IndexHeading": _SI.INDEX_HEADING,
    "Caption": _SI.CAPTION,
    "TableofFigures": _SI.TABLE_OF_FIGURES,
    "EnvelopeAddress": _SI.ENVELOPE_ADDRESS,
    "EnvelopeReturn": _SI.ENVELOPE_RETURN,
    "FootnoteReference": _SI.FOOTNOTE_REFERENCE,
    "CommentReference": _SI.COMMENT_REFERENCE,
    "LineNumber": _SI.LINE_NUMBER,
    "PageNumber": _SI.PAGE_NUMBER,
    "EndnoteReference": _SI.ENDNOTE_REFERENCE,
    "EndnoteText": _SI.ENDNOTE_TEXT,
    "TableofAuthorities": _SI.TABLE_OF_AUTHORITIES,
    "MacroText": _SI.MACRO,
    "TOAHeading": _SI.TOA_HEADING,
    "List": _SI.LIST,
    "ListBullet": _SI.LIST_BULLET,
    "ListNumber": _SI.LIST_NUMBER,
    "List2": _SI.LIST_2,
    "List3": _SI.LIST_3,
    "List4": _SI.LIST_4,
    "List5": _SI.LIST_5,
    "ListBullet2": _SI.LIST_BULLET_2,
    "ListBullet3": _SI.LIST_BULLET_3,
    "ListBullet4": _SI.LIST_BULLET_4,
    "ListBullet5": _SI.LIST_BULLET_5,
    "ListNumber2": _SI.LIST_NUMBER_2,
    "ListNumber3": _SI.LIST_NUMBER_3,
    "ListNumber4": _SI.LIST_NUMBER_4,
    "ListNumber5": _SI.LIST_NUMBER_5,
    "Title": _SI.TITLE,
    "Closing": _SI.CLOSING,
    "Signature": _SI.SIGNATURE,
    "DefaultParagraphFont": _SI.DEFAULT_PARAGRAPH_FONT,
    "BodyText": _SI.BODY_TEXT,
    "BodyTextIndent": _SI.BODY_TEXT_INDENT,
    "ListContinue": _SI.LIST_CONTINUE,
    "ListContinue2": _SI.LIST_CONTINUE_2,
    "ListContinue3": _SI.LIST_CONTINUE_3,
    "ListContinue4": _SI.LIST_CONTINUE_4,
    "ListContinue5": _SI.LIST_CONTINUE_5,
    "MessageHeader": _SI.MESSAGE_HEADER,
    "Subtitle": _SI.SUBTITLE,
    "Salutation": _SI.SALUTATION,
    "Date": _SI.DATE,
    "BodyTextFirstIndent": _SI.BODY_TEXT_FIRST_INDENT,
    "BodyTextFirstIndent2": _SI.BODY_TEXT_FIRST_INDENT_2,
    "NoteHeading": _SI.NOTE_HEADING,
    "BodyText2": _SI.BODY_TEXT_2,
    "BodyText3": _SI.BODY_TEXT_3,
    "BodyTextIndent2": _SI.BODY_TEXT_INDENT_2,
    "BodyTextIndent3": _SI.BODY_TEXT_INDENT_3,
    "BlockText": _SI.BLOCK_TEXT,
    "Hyperlink": _SI.HYPERLINK,
    "FollowedHyperlink": _SI.FOLLOWED_HYPERLINK,
    "Strong": _SI.STRONG,
    "Emphasis": _SI.EMPHASIS,
    "DocumentMap": _SI.DOCUMENT_MAP,
    "PlainText": _SI.PLAIN_TEXT,
    "E-mailSignature": _SI.EMAIL_SIGNATURE,
    "HTMLTopofForm": _SI.HTML_TOP_OF_FORM,
    "HTMLBottomofForm": _SI.HTML_BOTTOM_OF_FORM,
    "NormalWeb": _SI.NORMAL_WEB,
    "HTMLAcronym": _SI.HTML_ACRONYM,
    "HTMLAddress": _SI.HTML_ADDRESS,
    "HTMLCite": _SI.HTML_CITE,
    "HTMLCode": _SI.HTML_CODE,
    "HTMLDefinition": _SI.HTML_DEFINITION,
    "HTMLKeyboard": _SI.HTML_KEYBOARD,
    "HTMLPreformatted": _SI.HTML_PREFORMATTED,
    "HTMLSample": _SI.HTML_SAMPLE,
    "HTMLTypewriter": _SI.HTML_TYPEWRITER,
    "HTMLVariable": _SI.HTML_VARIABLE,
    "NormalTable": _SI.TABLE_NORMAL,
    "TableNormal": _SI.TABLE_NORMAL,
    "CommentSubject": _SI.COMMENT_SUBJECT,
    "NoList": _SI.NO_LIST,
    "OutlineList1": _SI.OUTLINE_LIST_1,
    "OutlineList2": _SI.OUTLINE_LIST_2,
    "OutlineList3": _SI.OUTLINE_LIST_3,
    "BalloonText": _SI.BALLOON_TEXT,
    "TableGrid": _SI.TABLE_GRID,
    "PlaceholderText": _SI.PLACEHOLDER_TEXT,
    "NoSpacing": _SI.NO_SPACING,
    "ListParagraph": _SI.LIST_PARAGRAPH,
    "Quote": _SI.QUOTE,
    "IntenseQuote": _SI.INTENSE_QUOTE,
    "SubtleEmphasis": _SI.SUBTLE_EMPHASIS,
    "IntenseEmphasis": _SI.INTENSE_EMPHASIS,
    "SubtleReference": _SI.SUBTLE_REFERENCE,
    "IntenseReference": _SI.INTENSE_REFERENCE,
    "BookTitle": _SI.BOOK_TITLE,
    "Bibliography": _SI.BIBLIOGRAPHY,
    "TOCHeading": _SI.TOC_HEADING,
    "Revision": _SI.REVISION,
    "SmartLink": _SI.SMART_LINK,
    "Mention": _SI.MENTION,
    "SmartHyperlink": _SI.SMART_HYPERLINK,
    "Hashtag": _SI.HASHTAG,
    "UnresolvedMention": _SI.UNRESOLVED_MENTION,
    # Legacy table styles.
    "TableSimple1": _SI.TABLE_SIMPLE_1,
    "TableSimple2": _SI.TABLE_SIMPLE_2,
    "TableSimple3": _SI.TABLE_SIMPLE_3,
    "TableClassic1": _SI.TABLE_CLASSIC_1,
    "TableClassic2": _SI.TABLE_CLASSIC_2,
    "TableClassic3": _SI.TABLE_CLASSIC_3,
    "TableClassic4": _SI.TABLE_CLASSIC_4,
    "TableColorful1": _SI.TABLE_COLORFUL_1,
    "TableColorful2": _SI.TABLE_COLORFUL_2,
    "TableColorful3": _SI.TABLE_COLORFUL_3,
    "TableColumns1": _SI.TABLE_COLUMNS_1,
    "TableColumns2": _SI.TABLE_COLUMNS_2,
    "TableColumns3": _SI.TABLE_COLUMNS_3,
    "TableColumns4": _SI.TABLE_COLUMNS_4,
    "TableColumns5": _SI.TABLE_COLUMNS_5,
    "TableGrid1": _SI.TABLE_GRID_1,
    "TableGrid2": _SI.TABLE_GRID_2,
    "TableGrid3": _SI.TABLE_GRID_3,
    "TableGrid4": _SI.TABLE_GRID_4,
    "TableGrid5": _SI.TABLE_GRID_5,
    "TableGrid6": _SI.TABLE_GRID_6,
    "TableGrid7": _SI.TABLE_GRID_7,
    "TableGrid8": _SI.TABLE_GRID_8,
    "TableList1": _SI.TABLE_LIST_1,
    "TableList2": _SI.TABLE_LIST_2,
    "TableList3": _SI.TABLE_LIST_3,
    "TableList4": _SI.TABLE_LIST_4,
    "TableList5": _SI.TABLE_LIST_5,
    "TableList6": _SI.TABLE_LIST_6,
    "TableList7": _SI.TABLE_LIST_7,
    "TableList8": _SI.TABLE_LIST_8,
    "Table3Deffects1": _SI.TABLE_3D_EFFECTS_1,
    "Table3Deffects2": _SI.TABLE_3D_EFFECTS_2,
    "Table3Deffects3": _SI.TABLE_3D_EFFECTS_3,
    "TableContemporary": _SI.TABLE_CONTEMPORARY,
    "TableElegant": _SI.TABLE_ELEGANT,
    "TableProfessional": _SI.TABLE_PROFESSIONAL,
    "TableSubtle1": _SI.TABLE_SUBTLE_1,
    "TableSubtle2": _SI.TABLE_SUBTLE_2,
    "TableTheme": _SI.TABLE_THEME,
    "TableWeb1": _SI.TABLE_WEB_1,
    "TableWeb2": _SI.TABLE_WEB_2,
    "TableWeb3": _SI.TABLE_WEB_3,
    # Word 2007+ accent table styles.
    "LightShading": _SI.LIGHT_SHADING,
    "LightList": _SI.LIGHT_LIST,
    "LightGrid": _SI.LIGHT_GRID,
    "MediumShading1": _SI.MEDIUM_SHADING_1,
    "MediumShading2": _SI.MEDIUM_SHADING_2,
    "MediumList1": _SI.MEDIUM_LIST_1,
    "MediumList2": _SI.MEDIUM_LIST_2,
    "MediumGrid1": _SI.MEDIUM_GRID_1,
    "MediumGrid2": _SI.MEDIUM_GRID_2,
    "MediumGrid3": _SI.MEDIUM_GRID_3,
    "DarkList": _SI.DARK_LIST,
    "ColorfulShading": _SI.COLORFUL_SHADING,
    "ColorfulList": _SI.COLORFUL_LIST,
    "ColorfulGrid": _SI.COLORFUL_GRID,
    "LightShading-Accent1": _SI.LIGHT_SHADING_ACCENT_1,
    "LightList-Accent1": _SI.LIGHT_LIST_ACCENT_1,
    "LightGrid-Accent1": _SI.LIGHT_GRID_ACCENT_1,
    "MediumShading1-Accent1": _SI.MEDIUM_SHADING_1_ACCENT_1,
    "MediumShading2-Accent1": _SI.MEDIUM_SHADING_2_ACCENT_1,
    "MediumList1-Accent1": _SI.MEDIUM_LIST_1_ACCENT_1,
    "MediumList2-Accent1": _SI.MEDIUM_LIST_2_ACCENT_1,
    "MediumGrid1-Accent1": _SI.MEDIUM_GRID_1_ACCENT_1,
    "MediumGrid2-Accent1": _SI.MEDIUM_GRID_2_ACCENT_1,
    "MediumGrid3-Accent1": _SI.MEDIUM_GRID_3_ACCENT_1,
    "DarkList-Accent1": _SI.DARK_LIST_ACCENT_1,
    "ColorfulShading-Accent1": _SI.COLORFUL_SHADING_ACCENT_1,
    "ColorfulList-Accent1": _SI.COLORFUL_LIST_ACCENT_1,
    "ColorfulGrid-Accent1": _SI.COLORFUL_GRID_ACCENT_1,
    "LightShading-Accent2": _SI.LIGHT_SHADING_ACCENT_2,
    "LightList-Accent2": _SI.LIGHT_LIST_ACCENT_2,
    "LightGrid-Accent2": _SI.LIGHT_GRID_ACCENT_2,
    "MediumShading1-Accent2": _SI.MEDIUM_SHADING_1_ACCENT_2,
    "MediumShading2-Accent2": _SI.MEDIUM_SHADING_2_ACCENT_2,
    "MediumList1-Accent2": _SI.MEDIUM_LIST_1_ACCENT_2,
    "MediumList2-Accent2": _SI.MEDIUM_LIST_2_ACCENT_2,
    "MediumGrid1-Accent2": _SI.MEDIUM_GRID_1_ACCENT_2,
    "MediumGrid2-Accent2": _SI.MEDIUM_GRID_2_ACCENT_2,
    "MediumGrid3-Accent2": _SI.MEDIUM_GRID_3_ACCENT_2,
    "DarkList-Accent2": _SI.DARK_LIST_ACCENT_2,
    "ColorfulShading-Accent2": _SI.COLORFUL_SHADING_ACCENT_2,
    "ColorfulList-Accent2": _SI.COLORFUL_LIST_ACCENT_2,
    "ColorfulGrid-Accent2": _SI.COLORFUL_GRID_ACCENT_2,
    "LightShading-Accent3": _SI.LIGHT_SHADING_ACCENT_3,
    "LightList-Accent3": _SI.LIGHT_LIST_ACCENT_3,
    "LightGrid-Accent3": _SI.LIGHT_GRID_ACCENT_3,
    "MediumShading1-Accent3": _SI.MEDIUM_SHADING_1_ACCENT_3,
    "MediumShading2-Accent3": _SI.MEDIUM_SHADING_2_ACCENT_3,
    "MediumList1-Accent3": _SI.MEDIUM_LIST_1_ACCENT_3,
    "MediumList2-Accent3": _SI.MEDIUM_LIST_2_ACCENT_3,
    "MediumGrid1-Accent3": _SI.MEDIUM_GRID_1_ACCENT_3,
    "MediumGrid2-Accent3": _SI.MEDIUM_GRID_2_ACCENT_3,
    "MediumGrid3-Accent3": _SI.MEDIUM_GRID_3_ACCENT_3,
    "DarkList-Accent3": _SI.DARK_LIST_ACCENT_3,
    "ColorfulShading-Accent3": _SI.COLORFUL_SHADING_ACCENT_3,
    "ColorfulList-Accent3": _SI.COLORFUL_LIST_ACCENT_3,
    "ColorfulGrid-Accent3": _SI.COLORFUL_GRID_ACCENT_3,
    "LightShading-Accent4": _SI.LIGHT_SHADING_ACCENT_4,
    "LightList-Accent4": _SI.LIGHT_LIST_ACCENT_4,
    "LightGrid-Accent4": _SI.LIGHT_GRID_ACCENT_4,
    "MediumShading1-Accent4": _SI.MEDIUM_SHADING_1_ACCENT_4,
    "MediumShading2-Accent4": _SI.MEDIUM_SHADING_2_ACCENT_4,
    "MediumList1-Accent4": _SI.MEDIUM_LIST_1_ACCENT_4,
    "MediumList2-Accent4": _SI.MEDIUM_LIST_2_ACCENT_4,
    "MediumGrid1-Accent4": _SI.MEDIUM_GRID_1_ACCENT_4,
    "MediumGrid2-Accent4": _SI.MEDIUM_GRID_2_ACCENT_4,
    "MediumGrid3-Accent4": _SI.MEDIUM_GRID_3_ACCENT_4,
    "DarkList-Accent4": _SI.DARK_LIST_ACCENT_4,
    "ColorfulShading-Accent4": _SI.COLORFUL_SHADING_ACCENT_4,
    "ColorfulList-Accent4": _SI.COLORFUL_LIST_ACCENT_4,
    "ColorfulGrid-Accent4": _SI.COLORFUL_GRID_ACCENT_4,
    "LightShading-Accent5": _SI.LIGHT_SHADING_ACCENT_5,
    "LightList-Accent5": _SI.LIGHT_LIST_ACCENT_5,
    "LightGrid-Accent5": _SI.LIGHT_GRID_ACCENT_5,
    "MediumShading1-Accent5": _SI.MEDIUM_SHADING_1_ACCENT_5,
    "MediumShading2-Accent5": _SI.MEDIUM_SHADING_2_ACCENT_5,
    "MediumList1-Accent5": _SI.MEDIUM_LIST_1_ACCENT_5,
    "MediumList2-Accent5": _SI.MEDIUM_LIST_2_ACCENT_5,
    "MediumGrid1-Accent5": _SI.MEDIUM_GRID_1_ACCENT_5,
    "MediumGrid2-Accent5": _SI.MEDIUM_GRID_2_ACCENT_5,
    "MediumGrid3-Accent5": _SI.MEDIUM_GRID_3_ACCENT_5,
    "DarkList-Accent5": _SI.DARK_LIST_ACCENT_5,
    "ColorfulShading-Accent5": _SI.COLORFUL_SHADING_ACCENT_5,
    "ColorfulList-Accent5": _SI.COLORFUL_LIST_ACCENT_5,
    "ColorfulGrid-Accent5": _SI.COLORFUL_GRID_ACCENT_5,
    "LightShading-Accent6": _SI.LIGHT_SHADING_ACCENT_6,
    "LightList-Accent6": _SI.LIGHT_LIST_ACCENT_6,
    "LightGrid-Accent6": _SI.LIGHT_GRID_ACCENT_6,
    "MediumShading1-Accent6": _SI.MEDIUM_SHADING_1_ACCENT_6,
    "MediumShading2-Accent6": _SI.MEDIUM_SHADING_2_ACCENT_6,
    "MediumList1-Accent6": _SI.MEDIUM_LIST_1_ACCENT_6,
    "MediumList2-Accent6": _SI.MEDIUM_LIST_2_ACCENT_6,
    "MediumGrid1-Accent6": _SI.MEDIUM_GRID_1_ACCENT_6,
    "MediumGrid2-Accent6": _SI.MEDIUM_GRID_2_ACCENT_6,
    "MediumGrid3-Accent6": _SI.MEDIUM_GRID_3_ACCENT_6,
    "DarkList-Accent6": _SI.DARK_LIST_ACCENT_6,
    "ColorfulShading-Accent6": _SI.COLORFUL_SHADING_ACCENT_6,
    "ColorfulList-Accent6": _SI.COLORFUL_LIST_ACCENT_6,
    "ColorfulGrid-Accent6": _SI.COLORFUL_GRID_ACCENT_6,
    # Word 2013+ new table styles.
    "PlainTable1": _SI.PLAIN_TABLE_1,
    "PlainTable2": _SI.PLAIN_TABLE_2,
    "PlainTable3": _SI.PLAIN_TABLE_3,
    "PlainTable4": _SI.PLAIN_TABLE_4,
    "PlainTable5": _SI.PLAIN_TABLE_5,
    "TableGridLight": _SI.TABLE_GRID_LIGHT,
    "GridTable1Light": _SI.GRID_TABLE_1_LIGHT,
    "GridTable2": _SI.GRID_TABLE_2,
    "GridTable3": _SI.GRID_TABLE_3,
    "GridTable4": _SI.GRID_TABLE_4,
    "GridTable5Dark": _SI.GRID_TABLE_5_DARK,
    "GridTable6Colorful": _SI.GRID_TABLE_6_COLORFUL,
    "GridTable7Colorful": _SI.GRID_TABLE_7_COLORFUL,
    "GridTable1Light-Accent1": _SI.GRID_TABLE_1_LIGHT_ACCENT_1,
    "GridTable2-Accent1": _SI.GRID_TABLE_2_ACCENT_1,
    "GridTable3-Accent1": _SI.GRID_TABLE_3_ACCENT_1,
    "GridTable4-Accent1": _SI.GRID_TABLE_4_ACCENT_1,
    "GridTable5Dark-Accent1": _SI.GRID_TABLE_5_DARK_ACCENT_1,
    "GridTable6Colorful-Accent1": _SI.GRID_TABLE_6_COLORFUL_ACCENT_1,
    "GridTable7Colorful-Accent1": _SI.GRID_TABLE_7_COLORFUL_ACCENT_1,
    "GridTable1Light-Accent2": _SI.GRID_TABLE_1_LIGHT_ACCENT_2,
    "GridTable2-Accent2": _SI.GRID_TABLE_2_ACCENT_2,
    "GridTable3-Accent2": _SI.GRID_TABLE_3_ACCENT_2,
    "GridTable4-Accent2": _SI.GRID_TABLE_4_ACCENT_2,
    "GridTable5Dark-Accent2": _SI.GRID_TABLE_5_DARK_ACCENT_2,
    "GridTable6Colorful-Accent2": _SI.GRID_TABLE_6_COLORFUL_ACCENT_2,
    "GridTable7Colorful-Accent2": _SI.GRID_TABLE_7_COLORFUL_ACCENT_2,
    "GridTable1Light-Accent3": _SI.GRID_TABLE_1_LIGHT_ACCENT_3,
    "GridTable2-Accent3": _SI.GRID_TABLE_2_ACCENT_3,
    "GridTable3-Accent3": _SI.GRID_TABLE_3_ACCENT_3,
    "GridTable4-Accent3": _SI.GRID_TABLE_4_ACCENT_3,
    "GridTable5Dark-Accent3": _SI.GRID_TABLE_5_DARK_ACCENT_3,
    "GridTable6Colorful-Accent3": _SI.GRID_TABLE_6_COLORFUL_ACCENT_3,
    "GridTable7Colorful-Accent3": _SI.GRID_TABLE_7_COLORFUL_ACCENT_3,
    "GridTable1Light-Accent4": _SI.GRID_TABLE_1_LIGHT_ACCENT_4,
    "GridTable2-Accent4": _SI.GRID_TABLE_2_ACCENT_4,
    "GridTable3-Accent4": _SI.GRID_TABLE_3_ACCENT_4,
    "GridTable4-Accent4": _SI.GRID_TABLE_4_ACCENT_4,
    "GridTable5Dark-Accent4": _SI.GRID_TABLE_5_DARK_ACCENT_4,
    "GridTable6Colorful-Accent4": _SI.GRID_TABLE_6_COLORFUL_ACCENT_4,
    "GridTable7Colorful-Accent4": _SI.GRID_TABLE_7_COLORFUL_ACCENT_4,
    "GridTable1Light-Accent5": _SI.GRID_TABLE_1_LIGHT_ACCENT_5,
    "GridTable2-Accent5": _SI.GRID_TABLE_2_ACCENT_5,
    "GridTable3-Accent5": _SI.GRID_TABLE_3_ACCENT_5,
    "GridTable4-Accent5": _SI.GRID_TABLE_4_ACCENT_5,
    "GridTable5Dark-Accent5": _SI.GRID_TABLE_5_DARK_ACCENT_5,
    "GridTable6Colorful-Accent5": _SI.GRID_TABLE_6_COLORFUL_ACCENT_5,
    "GridTable7Colorful-Accent5": _SI.GRID_TABLE_7_COLORFUL_ACCENT_5,
    "GridTable1Light-Accent6": _SI.GRID_TABLE_1_LIGHT_ACCENT_6,
    "GridTable2-Accent6": _SI.GRID_TABLE_2_ACCENT_6,
    "GridTable3-Accent6": _SI.GRID_TABLE_3_ACCENT_6,
    "GridTable4-Accent6": _SI.GRID_TABLE_4_ACCENT_6,
    "GridTable5Dark-Accent6": _SI.GRID_TABLE_5_DARK_ACCENT_6,
    "GridTable6Colorful-Accent6": _SI.GRID_TABLE_6_COLORFUL_ACCENT_6,
    "GridTable7Colorful-Accent6": _SI.GRID_TABLE_7_COLORFUL_ACCENT_6,
    "ListTable1Light": _SI.LIST_TABLE_1_LIGHT,
    "ListTable2": _SI.LIST_TABLE_2,
    "ListTable3": _SI.LIST_TABLE_3,
    "ListTable4": _SI.LIST_TABLE_4,
    "ListTable5Dark": _SI.LIST_TABLE_5_DARK,
    "ListTable6Colorful": _SI.LIST_TABLE_6_COLORFUL,
    "ListTable7Colorful": _SI.LIST_TABLE_7_COLORFUL,
    "ListTable1Light-Accent1": _SI.LIST_TABLE_1_LIGHT_ACCENT_1,
    "ListTable2-Accent1": _SI.LIST_TABLE_2_ACCENT_1,
    "ListTable3-Accent1": _SI.LIST_TABLE_3_ACCENT_1,
    "ListTable4-Accent1": _SI.LIST_TABLE_4_ACCENT_1,
    "ListTable5Dark-Accent1": _SI.LIST_TABLE_5_DARK_ACCENT_1,
    "ListTable6Colorful-Accent1": _SI.LIST_TABLE_6_COLORFUL_ACCENT_1,
    "ListTable7Colorful-Accent1": _SI.LIST_TABLE_7_COLORFUL_ACCENT_1,
    "ListTable1Light-Accent2": _SI.LIST_TABLE_1_LIGHT_ACCENT_2,
    "ListTable2-Accent2": _SI.LIST_TABLE_2_ACCENT_2,
    "ListTable3-Accent2": _SI.LIST_TABLE_3_ACCENT_2,
    "ListTable4-Accent2": _SI.LIST_TABLE_4_ACCENT_2,
    "ListTable5Dark-Accent2": _SI.LIST_TABLE_5_DARK_ACCENT_2,
    "ListTable6Colorful-Accent2": _SI.LIST_TABLE_6_COLORFUL_ACCENT_2,
    "ListTable7Colorful-Accent2": _SI.LIST_TABLE_7_COLORFUL_ACCENT_2,
    "ListTable1Light-Accent3": _SI.LIST_TABLE_1_LIGHT_ACCENT_3,
    "ListTable2-Accent3": _SI.LIST_TABLE_2_ACCENT_3,
    "ListTable3-Accent3": _SI.LIST_TABLE_3_ACCENT_3,
    "ListTable4-Accent3": _SI.LIST_TABLE_4_ACCENT_3,
    "ListTable5Dark-Accent3": _SI.LIST_TABLE_5_DARK_ACCENT_3,
    "ListTable6Colorful-Accent3": _SI.LIST_TABLE_6_COLORFUL_ACCENT_3,
    "ListTable7Colorful-Accent3": _SI.LIST_TABLE_7_COLORFUL_ACCENT_3,
    "ListTable1Light-Accent4": _SI.LIST_TABLE_1_LIGHT_ACCENT_4,
    "ListTable2-Accent4": _SI.LIST_TABLE_2_ACCENT_4,
    "ListTable3-Accent4": _SI.LIST_TABLE_3_ACCENT_4,
    "ListTable4-Accent4": _SI.LIST_TABLE_4_ACCENT_4,
    "ListTable5Dark-Accent4": _SI.LIST_TABLE_5_DARK_ACCENT_4,
    "ListTable6Colorful-Accent4": _SI.LIST_TABLE_6_COLORFUL_ACCENT_4,
    "ListTable7Colorful-Accent4": _SI.LIST_TABLE_7_COLORFUL_ACCENT_4,
    "ListTable1Light-Accent5": _SI.LIST_TABLE_1_LIGHT_ACCENT_5,
    "ListTable2-Accent5": _SI.LIST_TABLE_2_ACCENT_5,
    "ListTable3-Accent5": _SI.LIST_TABLE_3_ACCENT_5,
    "ListTable4-Accent5": _SI.LIST_TABLE_4_ACCENT_5,
    "ListTable5Dark-Accent5": _SI.LIST_TABLE_5_DARK_ACCENT_5,
    "ListTable6Colorful-Accent5": _SI.LIST_TABLE_6_COLORFUL_ACCENT_5,
    "ListTable7Colorful-Accent5": _SI.LIST_TABLE_7_COLORFUL_ACCENT_5,
    "ListTable1Light-Accent6": _SI.LIST_TABLE_1_LIGHT_ACCENT_6,
    "ListTable2-Accent6": _SI.LIST_TABLE_2_ACCENT_6,
    "ListTable3-Accent6": _SI.LIST_TABLE_3_ACCENT_6,
    "ListTable4-Accent6": _SI.LIST_TABLE_4_ACCENT_6,
    "ListTable5Dark-Accent6": _SI.LIST_TABLE_5_DARK_ACCENT_6,
    "ListTable6Colorful-Accent6": _SI.LIST_TABLE_6_COLORFUL_ACCENT_6,
    "ListTable7Colorful-Accent6": _SI.LIST_TABLE_7_COLORFUL_ACCENT_6,
}

IDENTIFIER_TO_STYLE_ID: dict[int, str] = {v: k for k, v in STYLE_ID_TO_IDENTIFIER.items()}

# Name-based fallback lookup: canonicalized ``w:name`` (lowercase, no spaces)
# -> StyleIdentifier.  Used when the styleId itself is non-standard
# (e.g. numeric "1" instead of "Heading1").
_NAME_TO_IDENTIFIER: dict[str, int] = {
    k.lower(): v for k, v in STYLE_ID_TO_IDENTIFIER.items()
}
# Add common w:name forms (with spaces, lowercase)
_NAME_TO_IDENTIFIER.update({
    "heading 1": _SI.HEADING_1,
    "heading 2": _SI.HEADING_2,
    "heading 3": _SI.HEADING_3,
    "heading 4": _SI.HEADING_4,
    "heading 5": _SI.HEADING_5,
    "heading 6": _SI.HEADING_6,
    "heading 7": _SI.HEADING_7,
    "heading 8": _SI.HEADING_8,
    "heading 9": _SI.HEADING_9,
    "body text": _SI.BODY_TEXT,
    "body text 2": _SI.BODY_TEXT_2,
    "body text 3": _SI.BODY_TEXT_3,
    "body text indent": _SI.BODY_TEXT_INDENT,
    "body text indent 2": _SI.BODY_TEXT_INDENT_2,
    "body text indent 3": _SI.BODY_TEXT_INDENT_3,
    "body text first indent": _SI.BODY_TEXT_FIRST_INDENT,
    "body text first indent 2": _SI.BODY_TEXT_FIRST_INDENT_2,
    "comment text": _SI.COMMENT_TEXT,
    "comment reference": _SI.COMMENT_REFERENCE,
    "comment subject": _SI.COMMENT_SUBJECT,
    "footnote text": _SI.FOOTNOTE_TEXT,
    "footnote reference": _SI.FOOTNOTE_REFERENCE,
    "endnote text": _SI.ENDNOTE_TEXT,
    "endnote reference": _SI.ENDNOTE_REFERENCE,
    "default paragraph font": _SI.DEFAULT_PARAGRAPH_FONT,
    "table normal": _SI.TABLE_NORMAL,
    "normal table": _SI.TABLE_NORMAL,
    "no list": _SI.NO_LIST,
    "list paragraph": _SI.LIST_PARAGRAPH,
    "table grid": _SI.TABLE_GRID,
    "normal indent": _SI.NORMAL_INDENT,
    "toc heading": _SI.TOC_HEADING,
    "toa heading": _SI.TOA_HEADING,
    "envelope address": _SI.ENVELOPE_ADDRESS,
    "envelope return": _SI.ENVELOPE_RETURN,
    "index heading": _SI.INDEX_HEADING,
    "table of figures": _SI.TABLE_OF_FIGURES,
    "table of authorities": _SI.TABLE_OF_AUTHORITIES,
    "macro text": _SI.MACRO,
    "list bullet": _SI.LIST_BULLET,
    "list number": _SI.LIST_NUMBER,
    "list continue": _SI.LIST_CONTINUE,
    "note heading": _SI.NOTE_HEADING,
    "block text": _SI.BLOCK_TEXT,
    "followed hyperlink": _SI.FOLLOWED_HYPERLINK,
    "document map": _SI.DOCUMENT_MAP,
    "plain text": _SI.PLAIN_TEXT,
    "message header": _SI.MESSAGE_HEADER,
    "email signature": _SI.EMAIL_SIGNATURE,
    "e-mail signature": _SI.EMAIL_SIGNATURE,
    "subtle emphasis": _SI.SUBTLE_EMPHASIS,
    "intense emphasis": _SI.INTENSE_EMPHASIS,
    "subtle reference": _SI.SUBTLE_REFERENCE,
    "intense reference": _SI.INTENSE_REFERENCE,
    "book title": _SI.BOOK_TITLE,
    "intense quote": _SI.INTENSE_QUOTE,
    "placeholder text": _SI.PLACEHOLDER_TEXT,
    "bibliography": _SI.BIBLIOGRAPHY,
    "revision": _SI.REVISION,
    "smart link": _SI.SMART_LINK,
    "smart hyperlink": _SI.SMART_HYPERLINK,
    "unresolved mention": _SI.UNRESOLVED_MENTION,
    "index 1": _SI.INDEX_1,
    "index 2": _SI.INDEX_2,
    "index 3": _SI.INDEX_3,
    "index 4": _SI.INDEX_4,
    "index 5": _SI.INDEX_5,
    "index 6": _SI.INDEX_6,
    "index 7": _SI.INDEX_7,
    "index 8": _SI.INDEX_8,
    "index 9": _SI.INDEX_9,
    "toc 1": _SI.TOC_1,
    "toc 2": _SI.TOC_2,
    "toc 3": _SI.TOC_3,
    "toc 4": _SI.TOC_4,
    "toc 5": _SI.TOC_5,
    "toc 6": _SI.TOC_6,
    "toc 7": _SI.TOC_7,
    "toc 8": _SI.TOC_8,
    "toc 9": _SI.TOC_9,
    "balloon text": _SI.BALLOON_TEXT,
    "normal (web)": _SI.NORMAL_WEB,
    "normal web": _SI.NORMAL_WEB,
    "no spacing": _SI.NO_SPACING,
    "list bullet 2": _SI.LIST_BULLET_2,
    "list bullet 3": _SI.LIST_BULLET_3,
    "list bullet 4": _SI.LIST_BULLET_4,
    "list bullet 5": _SI.LIST_BULLET_5,
    "list number 2": _SI.LIST_NUMBER_2,
    "list number 3": _SI.LIST_NUMBER_3,
    "list number 4": _SI.LIST_NUMBER_4,
    "list number 5": _SI.LIST_NUMBER_5,
    "list continue 2": _SI.LIST_CONTINUE_2,
    "list continue 3": _SI.LIST_CONTINUE_3,
    "list continue 4": _SI.LIST_CONTINUE_4,
    "list continue 5": _SI.LIST_CONTINUE_5,
    "html top of form": _SI.HTML_TOP_OF_FORM,
    "html bottom of form": _SI.HTML_BOTTOM_OF_FORM,
    "html preformatted": _SI.HTML_PREFORMATTED,
    "html address": _SI.HTML_ADDRESS,
    "html acronym": _SI.HTML_ACRONYM,
    "html cite": _SI.HTML_CITE,
    "html code": _SI.HTML_CODE,
    "html definition": _SI.HTML_DEFINITION,
    "html keyboard": _SI.HTML_KEYBOARD,
    "html sample": _SI.HTML_SAMPLE,
    "html typewriter": _SI.HTML_TYPEWRITER,
    "html variable": _SI.HTML_VARIABLE,
})


def resolve_style_identifier(style_id: str, style_name: str) -> int:
    """Resolve a style to its StyleIdentifier using styleId and name fallback.

    Tries the exact ``w:styleId`` first, then a case-insensitive match,
    then falls back to the ``w:name`` (canonicalized).  Names are looked
    up both with their literal lowercased form (``"page number"``) and
    with whitespace stripped (``"pagenumber"``) so locale-specific
    styleIds like Russian Word's ``"aff"`` (whose ``w:name`` is
    ``"page number"``) still resolve to ``PAGE_NUMBER``.
    """
    if style_id in STYLE_ID_TO_IDENTIFIER:
        return STYLE_ID_TO_IDENTIFIER[style_id]
    stripped = style_id.replace(" ", "")
    if stripped in STYLE_ID_TO_IDENTIFIER:
        return STYLE_ID_TO_IDENTIFIER[stripped]
    if style_name:
        lower = style_name.lower()
        if lower in _NAME_TO_IDENTIFIER:
            return _NAME_TO_IDENTIFIER[lower]
        # The lookup table is keyed by both the original styleId-style
        # form (``"PageNumber".lower()`` → ``"pagenumber"``) and a
        # hand-curated set of spaced display names (``"heading 1"``).
        # When the display name has spaces but no spaced entry exists,
        # fall back to the squashed form so the styleId-derived key
        # matches.
        squashed = lower.replace(" ", "")
        if squashed != lower and squashed in _NAME_TO_IDENTIFIER:
            return _NAME_TO_IDENTIFIER[squashed]
    return -1
